<div class="manage-area-nav">
    <h2><?= $this->layout()->firms[$this->layout()->fid]['name'] ?></h2>

    <div class="list project"></div>
    <div class="list region"></div>
    <?php
    if ($this->get('account')['puid'] == 0) {
        ?>
        <a class="unbind" href="javascript:void(0)">解除绑定</a>
    <?php } ?>
</div>
<div style="width: 100%;position: absolute;top:62px;bottom: 0;left: 0; overflow: hidden;">
    <iframe id="cdnpage" style="width: 100%;height:100%; border:none;"></iframe>
</div>

<script>
$(function () {
    $('.manage-area-nav .unbind').click(function () {
        if (confirm("确认解除绑定?")) {
            $.post(
                '/server-unbind/<?=$this->layout()->fid?>',
                {},
                function (ret) {
                    if (ret.code == 0) {
                        alert('解绑成功');
                        location.href = '/server-bind/<?=$this->layout()->fid?>'
                    } else {
                        if (ret.error) {
                            alert(ret.error);
                        } else {
                            alert('解绑失败');
                        }
                    }
                }
            );
        }
    });
    var sid = '<?=$sid?>';
    var username = '<?=$username?>';
    var url = 'http://cdn.cloud.ztgame.com/login/?sid=' + sid + '&lu='+ username +'&rurl=http://cdn.cloud.ztgame.com/domain_manage/';
    //window.open(url);
    $("#cdnpage").attr("src", url);
    $("#cdnpage").show();
})
</script>