<div class="manage-area-nav">
    <h2><?= $this->layout()->firms[$this->layout()->fid]['name'] ?></h2>

    <div class="list project"></div>
    <div class="list region"></div>
    <?php
    if ($this->get('account')['puid'] == 0) {
        ?>
        <a class="unbind" href="javascript:void(0)">解除绑定</a>
    <?php } ?>
</div>
<div class="toolbar-template" style="display: none;">
    <button class="btn btn-default new-instance-create" data-toggle="modal" data-target="#addInstance">创建</button>
    <button class="btn btn-default table_refresh">刷新</button>
    <button class="btn btn-forbidden btn-default instance-restart" disabled>重新启动</button>
    <div class="dropdown instances_operations">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true">
            更多操作
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <!--li class 禁止其他包含disabled的名称-->
            <li class="disabled start" operation="start"><a href="javascript:void(0)">开机</a></li>
            <li class="disabled stop" operation="stop"><a href="javascript:void(0)">关机</a></li>
            <li class="stop" operation="addToJumpServer"><a href="javascript:void(0)">添加到堡垒机</a></li>
            <!--<li class="stop" operation="renewInstance"><a href="javascript:void(0)">续费</a></li>-->

            <!--<li class="disabled"><a href="javascript:alert('敬请期待')">加载密钥</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">分配至项目</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">改名</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">调整网络</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">销毁</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">导出选中</a></li>
            <li class="disabled"><a href="javascript:alert('敬请期待')">导出全部</a></li>-->
        </ul>
    </div>
    <button class="btn btn-default table_export">导出Excel</button>
</div>
<div class="dataTable-container" style="width: 90%; margin: auto;">
    <table id="hosts" class="display" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>
                <input type="checkbox" class="tablecheck checkall"/>
            </th>
            <th>ID/主机名</th>
            <th>IP</th>
            <th>项目</th>
            <th>可用区</th>
            <th>状态</th>
            <th>主机计费模式</th>
            <th>到期时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>
                <input type="checkbox" class="tablecheck checkall"/>
            </th>
            <th>ID/主机名</th>
            <th>IP</th>
            <th>项目</th>
            <th>可用区</th>
            <th>状态</th>
            <th>主机计费模式</th>
            <th>到期时间</th>
            <th>操作</th>
        </tr>
        </tfoot>
    </table>
</div>
<div class="modal fade" id="addInstance" tabindex="-1" role="dialog" aria-labelledby="addInstance">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="addInstance">创建实例</h4>
</div>
<div class="modal-body">
<div>
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#baoyue" aria-controls="baoyue" role="tab"
                                              data-toggle="tab">包年包月</a></li>
    <li role="presentation"><a href="#anliang" aria-controls="anliang" role="tab" data-toggle="tab">按量计费</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<p><a target="_blank" href="https://www.qcloud.com/doc/product/213/CVM%E5%AE%9E%E4%BE%8B%E9%85%8D%E7%BD%AE"><span class="glyphicon glyphicon-info-sign"></span> 腾讯云主机实例配置</a></p>
<br>
<div role="tabpanel" class="tab-pane active" id="baoyue">
    <h4><b>创建包年包月的云主机</b></h4>
    <br>
    <!--包年包月-->
    <form>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">镜像类型</label>
                    <select class="form-control" name="imageType">
                        <option value=1>私有镜像</option>
                        <option value=2 selected>公共镜像</option>
                        <option value=3>服务市场</option>
                        <option value=4>共享镜像</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">镜像ID<span class="red">*</span></label>
                    <select class="form-control" name="imageId">
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">CPU核数<span class="red">*</span></label>
                    <select class="form-control" name="cpu">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="4">4</option>
                        <option value="8">8</option>
                        <option value="12">12</option>
                        <option value="16">16</option>
                        <option value="24">24</option>
                        <option value="32">32</option>
                        <option value="48">48</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">内存大小(单位GB)<span class="red">*</span></label>
                    <input type="number" class="form-control" name="mem">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">数据盘大小(单位:GB), 0 表示不要数据盘<span class="red">*</span></label>
                    <input type="number" step=10 class="form-control" name="storageSize">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">购买时长，单位(月),范围(1-36)<span class="red">*</span></label>
                    <input type="number" class="form-control" max=36 min=1 value="1" name="period">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">项目ID，不填为默认项目<span class="red">*</span></label>
                    <select class="form-control" name="projectId">
                        <option value="0">默认项目</option>
                        <?php
                        foreach ($this->projects as $id => $name) {
                            if ($id == 0) continue;
                            ?>
                            <option value="<?= $id ?>"><?= $name ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">可用区ID<span class="red">*</span></label>
                    <select class="form-control zoneId" name="zoneId">
                        <option value="200001" selected>上海一区</option>
                        <option value="800001">北京一区</option>
                        <option value="100002">广州二区</option>
                        <option value="100003">广州三区</option>
                        <option value="300001">香港一区</option>
                        <option value="400001">北美一区</option>
                    </select>
                </div>

            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">公网带宽（单位Mbps）</label>
                    <input type="number" class="form-control" name="bandwidth">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开通外网IP</label>
                    <select class="form-control" name="wanIp">
                        <option value="0">不开通</option>
                        <option value="1" selected>开通</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">带宽计费类型</label>
                    <select class="form-control" name="bandwidthType">
                        <option value="PayByTraffic">按流量计费</option>
                        <option value="PayByBandwidth" selected>按月计费</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">数据盘类型</label>
                    <select class="form-control" name="storageType">
                        <option value=1 selected>本地盘</option>
                        <option value=2>云硬盘</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">系统盘大小(单位:GB), 此参数需要联系官方客服开通权限</label>
                    <input type="number" class="form-control" name="rootSize">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">购买主机数量,范围(1-100)</label>
                    <input type="number" class="form-control" min=1 max=100 value=1 name="goodsNum">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">私有网络ID</label>
                    <input type="number" class="form-control" name="vpcId">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">子网ID</label>
                    <input type="text" class="form-control" name="subnetId">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">是否是自定义网关</label>
                    <select class="form-control" name="isVpcGateway">
                        <option value="0" selected>非自定义网关</option>
                        <option value="1">自定义网关</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开启云安全服务</label>
                    <select class="form-control" name="needSecurityAgent">
                        <option value="0">不开通</option>
                        <option value="1" selected>开通</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开启云监控服务</label>
                    <select class="form-control" name="needMonitorAgent">
                        <option value="0">不开通</option>
                        <option value="1" selected>开通</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">实例密码(至少要包含字母、数字、特殊字符!@#$%^*() 中的两种，且密码长度为8-16个字符)</label>
                    <input type="password" class="form-control" placeholder="未设置则密码为随机产生" maxlength="100"
                           name="password">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">密钥ID(密钥与密码不能同时指定)</label>
                    <input type="text" class="form-control" name="keyId">
                </div>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    </form>
</div>
<div role="tabpanel" class="tab-pane" id="anliang">
    <h4><b>创建按量计费的云主机</b></h4>
    <br>

    <form>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">镜像类型</label>
                    <select class="form-control" name="imageType">
                        <option value=1>私有镜像</option>
                        <option value=2 selected>公共镜像</option>
                        <option value=3>服务市场</option>
                        <option value=4>共享镜像</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">镜像ID<span class="red">*</span></label>
                    <select class="form-control" name="imageId">
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">CPU核数<span class="red">*</span></label>
                    <select class="form-control" name="cpu">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="4">4</option>
                        <option value="8">8</option>
                        <option value="12">12</option>
                        <option value="16">16</option>
                        <option value="24">24</option>
                        <option value="32">32</option>
                        <option value="48">48</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">内存大小(单位GB)<span class="red">*</span></label>
                    <input type="number" class="form-control" name="mem">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">数据盘大小(单位:GB), 0 表示不要数据盘<span class="red">*</span></label>
                    <input type="number" step=10 class="form-control" name="storageSize">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">可用区ID<span class="red">*</span></label>
                    <select class="form-control zoneId" name="zoneId">
                        <option value="200001" selected>上海一区</option>
                        <option value="800001">北京一区</option>
                        <option value="100002">广州二区</option>
                        <option value="100003">广州三区</option>
                        <option value="300001">香港一区</option>
                        <option value="400001">北美一区</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">公网带宽（单位Mbps）</label>
                    <input type="number" class="form-control" name="bandwidth">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开通外网IP</label>
                    <select class="form-control" name="wanIp">
                        <option value="0" selected>不开通</option>
                        <option value="1">开通</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">带宽计费类型</label>
                    <select class="form-control" name="bandwidthType">
                        <option value="PayByHour" selected>按带宽使用时长计费</option>
                        <option value="PayByTraffic">按流量计费</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">数据盘类型</label>
                    <select class="form-control" name="storageType">
                        <option value=1 selected>本地盘</option>
                        <option value=2>云硬盘</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">购买主机数量,范围(1-100)</label>
                    <input type="number" class="form-control" min=1 max=100 maxlength=3 value="1" name="goodsNum">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">实例密码(至少要包含字母、数字、特殊字符!@#$%^*() 中的两种，且密码长度为8-16个字符)</label>
                    <input type="password" class="form-control" placeholder="未设置则密码为随机产生" maxlength="100"
                           name="password">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">系统盘大小(单位:GB), 此参数需要联系官方客服开通权限</label>
                    <input type="number" class="form-control" name="rootSize">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">私有网络ID</label>
                    <input type="number" class="form-control" name="vpcId">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">子网ID</label>
                    <input type="text" class="form-control" name="subnetId">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">是否是自定义网关</label>
                    <select class="form-control" name="isVpcGateway">
                        <option value="0" selected>非自定义网关</option>
                        <option value="1">自定义网关</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开启云安全服务</label>
                    <select class="form-control" name="needSecurityAgent">
                        <option value="0">不开通</option>
                        <option value="1" selected>开通</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">开启云监控服务</label>
                    <select class="form-control" name="needMonitorAgent">
                        <option value="0">不开通</option>
                        <option value="1" selected>开通</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">项目ID，不填为默认项目</label>
                    <input type="text" class="form-control" name="projectId">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">密钥ID(密钥与密码不能同时指定)</label>
                    <input type="text" class="form-control" name="keyId">
                </div>
            </div>
        </div>
    </form>
</div>
</div>
</div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
    <button type="button" class="btn btn-primary" id="newPHAdd">创建</button>
</div>
</div>
</div>
</div>
<script>
$(function () {

    $('.manage-area-nav .unbind').click(function () {
        if (confirm("确认解除绑定?")) {
            $.post(
                '/server-unbind/<?=$this->layout()->fid?>',
                {},
                function (ret) {
                    if (ret.code == 0) {
                        alert('解绑成功');
                        location.href = '/server-bind/<?=$this->layout()->fid?>'
                    } else {
                        if (ret.error) {
                            alert(ret.error);
                        } else {
                            alert('解绑失败');
                        }
                    }
                }
            );
        }
    });
    var projects = <?=json_encode($projects)?>;
    var menus = [
        {
            name: '开机',
            func: function (menu) {
                var id = menu.attr('data-value');
                confirmModal("确认开机?", function () {
                    serverAction(id, 'start');
                });
            }
        },
        {
            name: '关机',
            func: function (menu) {
                var id = menu.attr('data-value');
                if (confirm("确认关机?")) {
                    serverAction(id, 'stop');
                }
            }
        },
        {
            name: '重新启动',
            func: function (menu) {
                var id = menu.attr('data-value');
                confirmModal("确认重启?", function () {
                    serverAction(id, 'restart');
                });
            }
        },
        {
            name: '修改密码',
            func: function (menu) {
                var id = menu.attr('data-value');
                window.confirmChangePass({id: id, desc: "实例密码 linux主机的密码规则是至少要包含字母、数字、特殊字符!@#$%^*() 中的两种，且密码长度为8-16个字符。 windows主机的密码规则是至少要包含大写字母、小写字母、数字、特殊字符!@#*中的三种，且密码长度为12-16个字符。"}, function (data) {
                    //console.log(1111);
                    serverAction(data.id, 'resetPassword', data.pass)
                });
            }
        },
        {
            name: '销毁',
            func: function (menu) {
                var id = menu.attr('data-value');
                confirmModal("确认销毁?", function () {
                    serverAction(id, 'returnInstance');
                });
            }
        },
        {
            name: '加入堡垒机',
            func: function (menu) {
                var id = menu.attr('data-value');
                var ip = menu.attr('data-wanip');
                var name = menu.attr('data-name');
                initJumpServerModal([
                    [id, ip, name]
                ]);
            }
        },
        {
            name: '添加到蓝鲸',
            func: function (menu) {
                var hostid = menu.attr('data-value');
                var wanip = menu.attr('data-wanip');
                var lanip = menu.attr('data-lanip');
                var name = menu.attr('data-name');
                showAddBWModal(
                    {
                        wanip : wanip,
                        lanip : lanip
                    },
                    function(id){
                        $.post(
                            '/m/add-to-blue-whale/100001',
                            {
                                wanip : wanip,
                                lanip : lanip,
                                appid : id,
                                hostid : hostid
                            },
                            function(ret) {
                                hideAddBWModal();
                                if(ret.code == 0)
                                {
                                    alert('添加成功');
                                } else if (ret.error) {
                                    alert(ret.error);
                                }
                            },
                            'json'
                        );
                });
            }
        },
        {
            name: '续费',
            func: function (menu) {
                var id = menu.attr('data-value');
                var ip = menu.attr('data-wanip');
                var name = menu.attr('data-name');
                showLoading();
                $.post(
                    '/m/get-price-by-id/100001',
                    {
                        id :id
                    },
                    function(ret)
                    {
                        hideLoading();
                        if(ret.code == 0)
                        {
                            if(ret.ret.price)
                            {
                                var price = ret.ret.price/100;
                                confirmModal("续费一个月(费用￥" + price + ")?",function(){
                                    $.post(
                                        '/m/renew-instance/<?=$this->layout()->fid?>',
                                        {
                                            id : id
                                        },
                                        function(ret)
                                        {
                                            if(ret.code == 0)
                                            {
                                                alert('续费成功');
                                            } else if(ret.error) {
                                                alert(ret.error);
                                            }
                                        },
                                        'json'
                                    );
                                });
                            } else {
                                alert(ret.ret);
                            }
                        } else {
                            alert(ret.error);
                        }

                    },
                    'json'
                );

            }
        }
    ];
    var tableDataURL = "/server-list/" + '<?=$this->layout()->fid?>';
    var tablePageLength = 10;
    var table = $('#hosts').DataTable({
        dom: '<"toolbar">frtip',
        processing: true,
        serverSide: true,
        ordering: false,
        searching: true,
        scrollX: true,
        //scrollY:300,
        scrollCollapse: false,
        searchDelay: 1000,
        pageLength: tablePageLength,
        displayStart: tablePageLength * <?=$get['n']?>,
        search: {
            search: "<?=$get['s']?>"
        },
        fixedColumns: {
            leftColumns: 0,
            rightColumns: 1
        },
        "ajax": {
            url: tableDataURL,
            type: 'POST',
            data: function (d) {
                d.p = $('.project').attr('data-value');
                d.r = $('.region').attr('data-value');
            }
        },
        "language": {
            "url": "/DataTables-1.10.11/media/languages/chinese.json",
            searchPlaceholder: '主机名或内网IP(IP,IP,IP...)'
        },
        'columns': [
            {
                "sClass": "text-center",
                "data": 'unId',
                render: function (data, type, full, meta) {
                    return '<p style="text-align: center;">' +
                        '<input type="checkbox"  class="tablecheck checkchild" operation-status="' + full.operationStatus + '"  value="' + data + '" />' +
                        '</p>';
                },
                "bSortable": false,
                "searchable": false
            },
            {
                'data': 'name',
                render: function (data, type, full, meta) {
                    var url = "/detail/<?=$this->layout()->fid?>/" + full.unId + '/' + full.rid;
                    return "<p><a href='javascript:void(0);' onclick=\"gotoDetail('"+url+"');\">" + full.unId + '</a></p><p>' + data + '</p>';
                },
                bSortable: false
            },
            {
                'data': 'lanIp',
                render: function (data, type, full, meta) {
                    return '<p>' + data + (full.wanIpSet ? ('(内网)</p><p>' + full.wanIpSet + '(公网)</p>') : '</p>');
                },
                bSortable: false,
                "searchable": false
            },
            {
                "data": 'pid',
                render: function (data, type, full, meta) {
                    return projects[data] || data;
                },
                "searchable": false
            },
            {
                "data": 'zoneName',
                "searchable": false
            },
            {
                "data": 'statusName',
                render: function (data, type, full, meta) {
                    return '<span class="status" style="color:#06c290;" status-value=' + full.status + '>' + data + '</span>';
                },
                "searchable": false
            },
            {
                "data": 'payMode',
                "searchable": false
            },
            {
                "data": 'deadlineTime',
                "searchable": false
            },
            {
                "sClass": "text-center",
                "data": 'unId',
                render: function (data, type, full, meta) {
                    /*'<a class="power-on"  data-value="' + data + '">开机</a> ' +
                     '<a class="power-off"  data-value="' + data + '">关机</a> ' +*/
                    return '<div class="operation" data-lanip="' + full.lanIp + '" data-wanip="' + full.wanIpSet + '" data-name="' + full.name + '" operation-status="' + full.operationStatus + '" data-value="' + data + '"><a>操作<span class="glyphicon glyphicon-menu-down"></span></a></div>';
                },
                "bSortable": false,
                "searchable": false
            }
        ],
        drawCallback: function (settings) {
            var api = this.api();
            $(".tablecheck").prop('checked', false);
            api.$(".checkchild").unbind().click(function () {
                changeBtnState()
            });
            $(".dataTable-container .toolbar").html($('.toolbar-template').html());
            for (var i = 0; i < api.$('tr').length; i++) {
                var tr = $(api.$('tr')[i]);
                var opStatus = tr.find('td div.operation').attr('operation-status');
                var statusList = [];
                for (var j = 0; j < opStatus.length; j++) {
                    statusList.push(parseInt(opStatus[j]));
                }
                tr.find(".operation").DropMenu(menus, statusList);
            }
            if (api.$('tr').length > 0) {
                $(".dataTable-container .table_export").removeClass('btn-forbidden').removeAttr('disabled');
            } else {
                $(".dataTable-container .table_export").addClass('btn-forbidden').attr('disabled', true);
            }
            $(".dataTable-container .table_refresh").unbind().click(function () {
                reload();
            });
            $(".dataTable-container .instance-restart").unbind().click(function () {
                var checkeds = $(".checkchild:checked");
                var serverIdsArr = [];
                for (var i = 0; i < checkeds.length; i++) {
                    serverIdsArr.push(checkeds[i].value);
                }
                var serverIds = serverIdsArr.join(',');
                if (confirm('确认重启?')) {
                    serverAction(serverIds, 'restart');
                }
            });

            $(".dataTable-container .table_export").unbind().click(function () {
                confirmModal(
                    '确认导出?',
                    function(data){
                        var p = $('.project').attr('data-value');
                        var r = $('.region').attr('data-value');
                        var searchInput = $('.dataTable-container input[type=search]');
                        var s = '';
                        if (searchInput.length > 0) {
                            s = searchInput.val();
                        }
                        var url = '/get-excel/<?=$this->layout()->fid?>';
                        $('#iframe-download').remove();
                        var frame = $('<iframe>');
                        frame.attr('id', 'iframe-download');
                        frame.attr('src', url + '?p=' + p + '&r=' + r + '&s=' + s);
                        frame.css('display', 'none');
                        $('body').append(frame);
                        alert('下载已经开始,请耐心等待,<code>不要重复操作</code>!');
                    }
                );

            });

            $('.dataTable-container .instances_operations li').unbind().click(function () {
                var me = $(this);
                if (me.hasClass('disabled')) {
                    return;
                }
                var action = me.attr('operation');
                if (action) {
                    if (action == 'addToJumpServer') {
                        var checkeds = $(".checkchild:checked");
                        var data = [];
                        for (var i = 0; i < checkeds.length; i++) {
                            var operation = $(checkeds[i]).parent('p').parent('td').parent('tr').find('.operation');
                            var id = operation.attr('data-value');
                            var ip = operation.attr('data-wanip');
                            var name = operation.attr('data-name');
                            data.push([id, ip, name])
                        }
                        initJumpServerModal(data);
                    } else if(action == 'renewInstance'){
                        var checkeds = $(".checkchild:checked");
                        var serverIdsArr = [];
                        for (var i = 0; i < checkeds.length; i++) {
                            serverIdsArr.push(checkeds[i].value);
                        }
                        console.log(serverIdsArr);
                        confirmModal(
                            '确认续费?',
                            function(data){
                                return false;
                                showLoading();
                                $.post(
                                    '/m/get-price-by-id/100001',
                                    {
                                        id :id
                                    },
                                    function(ret)
                                    {
                                        hideLoading();
                                        if(ret.code == 0)
                                        {
                                            if(ret.ret.price)
                                            {
                                                var price = ret.ret.price/100;
                                                confirmModal("续费一个月(费用￥" + price + ")?",function(){
                                                    $.post(
                                                        '/m/renew-instance/<?=$this->layout()->fid?>',
                                                        {
                                                            id : id
                                                        },
                                                        function(ret)
                                                        {
                                                            if(ret.code == 0)
                                                            {
                                                                alert('续费成功');
                                                            } else if(ret.error) {
                                                                alert(ret.error);
                                                            }
                                                        },
                                                        'json'
                                                    );
                                                });
                                            } else {
                                                alert(ret.ret);
                                            }
                                        } else {
                                            alert(ret.error);
                                        }

                                    },
                                    'json'
                                );
                            }
                        );

                    } else if (confirm('确认' + operations[action] + '?')) {
                        var checkeds = $(".checkchild:checked");
                        var serverIdsArr = [];
                        for (var i = 0; i < checkeds.length; i++) {
                            serverIdsArr.push(checkeds[i].value);
                        }
                        var serverIds = serverIdsArr.join(',');
                        serverAction(serverIds, action);
                    }
                }
            });
        }
    });
    window.gotoDetail = function(url)
    {
        var p = $('.project').attr('data-value');
        var r = $('.region').attr('data-value');
        var n = table.page();
        location.href=url;
    };
    $('.project').DropDownList(
        projects,
        function (id, name) {
            $('#hosts').dataTable().api().ajax.reload();
        },
        '<?=$get["p"]?>'//init seleted
    );
    $('.region').DropDownList(
        <?=json_encode($regions)?>,
        function (id, name) {
            $('#hosts').dataTable().api().ajax.reload();
        },
        '<?=$get["r"]?>'
    );
    $(".checkall").click(function () {
        var check = $(this).prop("checked");
        $(".checkchild").prop("checked", check);
        $(".checkall").prop("checked", check);
        changeBtnState();
    });
    function reload() {
        $('#hosts').dataTable().api().ajax.reload(function (json) {
        }, false);
    }

    var serverOperationURL = '/server-operation/' + '<?=$this->layout()->fid?>';

    function serverAction(ids, operationType, pass) {
        var pid = $('.project').attr('data-value');
        var rid = $('.region').attr('data-value');
        $.post(
            serverOperationURL,
            {
                serverIds: ids,
                action: operationType, //start|stop|restart
                pid: pid,
                rid: rid,
                password: pass
            },
            function (ret) {
                if (ret.code == 0) {
                    alert('操作成功完成');
                    ret.data && console.log(ret.data);
                } else {
                    alert(ret.error);
                }
                reload();
            },
            'json'
        )
    }

    var operations = {
        start: '开机',
        stop: '关机',
        restart: '重启'
    };

    function changeBtnState() {
        var opMenu = {
            start: 0,
            stop: 0,
            restart: 0
        };
        var checked = $(".checkchild:checked");
        for (var i = 0; i < checked.length; i++) {
            var opStatus = $(checked[i]).attr('operation-status');
            opMenu.start += parseInt(opStatus[0]);
            opMenu.stop += parseInt(opStatus[1]);
            opMenu.restart += parseInt(opStatus[2]);
        }
        if (!opMenu.restart) {
            $(".toolbar .instance-restart").addClass('btn-forbidden').attr('disabled', true);
        } else {
            $(".toolbar .instance-restart").removeClass('btn-forbidden').removeAttr('disabled');
        }
        var dropMenu = $('.instances_operations');
        if (opMenu.start) {
            dropMenu.find('.start').removeClass('disabled');
        } else {
            dropMenu.find('.start').addClass('disabled');
        }
        if (opMenu.stop) {
            dropMenu.find('.stop').removeClass('disabled');
        } else {
            dropMenu.find('.stop').addClass('disabled');
        }
    }

    $('#addInstance').on('show.bs.modal', function () {
        getImageList(2,function(data){
            var tab1 = $('#baoyue');
            var select1 = tab1.find('select[name=imageId]');
            var tab2 = $('#anliang');
            var select2 = tab2.find('select[name=imageId]');
            select1.empty();
            select2.empty();
            $.each(data, function(i,n){
                select1.append('<option value="' + i + '">' + n + '</option>');
                select2.append('<option value="' + i + '">' + n + '</option>');
            });
        });
        /*getZoneList(function(data){
            var select = $('select[name=zoneId]');
            console.log(select);
            select.empty();
            $.each(data, function(i,n){
                select.append('<option id="' + i + '">' + n + '</option>');
            });
        });*/
    });
    function getImageList(type,fn)
    {
        showLoading();
        $.post(
            '/get-image-list/100001',
            {
                type : type
            },
            function(ret){
                hideLoading();
                if(ret.code == 0) {
                    fn && fn(ret.data);
                }
            },
            'json'
        );
    }
    $('#addInstance select[name=imageType]').change(function(e){
        getImageList(e.target.value,function(data){
            var select = $(e.target).parent().parent().parent().find('select[name=imageId]');
            select.empty();
            $.each(data, function(i,n){
                select.append('<option id="' + i + '">' + n + '</option>');
            });
        });
    });
    function getZoneList(fn)
    {
        showLoading();
        $.post(
            '/m/get-zone-list/100001',
            {},
            function(ret){
                hideLoading();
                if(ret.code == 0) {
                    fn && fn(ret.ret);
                }
            },
            'json'
        );
    }
    $("#newPHAdd").click(function(){
        //getPrice();
        var $form = $('.tab-content>.active form');
        //@imageId@cpu@mem@storageSize@period
        if(!$form.find("select[name=imageId]").val())
        {
            alert('请选择镜像');
            return false;
        }
        if(!$form.find("select[name=cpu]").val())
        {
            alert('请选择CPU数');
            return false;
        }
        if(!$form.find("input[name=mem]").val())
        {
            alert('请填写内存');
            return false;
        }
        if(!$form.find("input[name=storageSize]").val())
        {
            alert('请数据盘大小');
            return false;
        }
        if($form.find("input[name=period]") && !$form.find("input[name=period]").val())
        {
            alert('请填写购买时长');
            return false;
        }
        if($form.find(".zoneId") && !$form.find(".zoneId").val())
        {
            alert('请选择可用区');
            return false;
        }
        showLoading();
        $.post(
            '/m/create-new-instance/100001',
            $form.serializeArray(),
            function(ret)
            {
                hideLoading();
                if(ret.code == 0)
                {
                    alert('创建成功');
                }
            },
            'json'
        );
    });
    function getPrice()
    {
        var $form = $('.tab-content>.active form');
        showLoading();
        $.post(
            '/m/get-price-by-config/100001',
            $form.serializeArray(),
            function(ret)
            {
                hideLoading();
                if(ret.code == 0)
                {
                    if(ret.ret.price)
                    {
                        alert('价格：￥' + ret.ret.price/100 * 0.75);
                    } else {
                        alert(ret.ret);
                    }
                } else {
                    alert(ret.error);
                }

            },
            'json'
        );
    }
})
</script>