<?php
$this->headTitle('关于我们');
?>
<div class="bannerguanyuwomen">
</div>
<div class="guanyu">
    <h2>关于我们</h2>
    <h3 class="guanyu1">技术团队</h3>
    <p>《云上云》是星云工作室技术团队影响市场需求,历史半年面相社会研发用户提供的混合云平台,目标是为国内外上万家企业用户提供免费云管云服务,通过自身拥有的专业优势最大程度降低企业发展所需的IT基础框架技术、成本门槛等。</p>
    <h3 class="guanyu2">我们的任务</h3>
    <p>我们把最全面的资源提供给您的团队！服务器提供99.95%服务可用性,99.999%数据可靠性的稳定服务。通过高性能服务器虚拟化为云服务器,提供自选配置类型虚拟机,可任意指定CPU、内存的数量,也充分在主机创建之后随时再行调整。多重实时副本保障您的数据安全,异地副本也能快速恢复,保证您的数据安全是我们时刻的使命。</p>
    <h3 class="guanyu3">我们的愿景</h3>
    <p>我们的愿景《云上云》致力于打造国内一流的混合云平台,实现云管云。我们希望协助更多的中小企业轻松实现传统IDC到云的跨越,享受云平台带来的稳定、安全、高效、高性价比,降低用户使用IT基础设施的技术门槛和成本。与此同事,依托巨人网络上百款游戏、十余年运营、数万台服务器、数十个机房的深厚运营经验,帮助用户赢在起点。</p>
</div>
<div class="footer">
    <h5>联系我们</h5>
    <ul>
        <li><img src="/towcloud/images/new/footer1.png">上海松江区中辰路655号</li>
        <li><img src="/towcloud/images/new/footer2.png">+(86)021-33979999 </li>
        <li><img src="/towcloud/images/new/footer3.png"><a href="mailto:contact@ztgame.com">lianbo@ztgame.com</a></li>
    </ul>
</div>
