<?php
    $this->headTitle('云分发CDN');
    $this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>

<div class="productwr">
    <div class="productwr1_7"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>申请流程</dt>
                <dd>
                    <a href="/login">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_17">
                <dt>极速用户体验</dt>
                <dd>
                    CDN服务将网站静态内容发布于离用户最近节点，用户可就近获得数据，提高页面访问速度和下载速度；广泛的CDN节点分布，保障用户的极致体验。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_14">
                <dt>高级防御</dt>
                <dd>企业级DDOS防御,快速准确识别CC攻击，实时阻断，隐藏源站IP,防止黑客获取源站信息。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_18">
                <dt>简单易用</dt>
                <dd>
                    自助化配置，完善错误提醒，配置项丰富，可定制控制访问、缓存策略等。
                    分析网站业务数据，提供报表。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_15">
                <dt>经济实惠</dt>
                <dd>
                    资源弹性扩展，按实际使用量付费
                    接入即可实现跨运营商、跨地域的全网覆盖
                </dd>
            </dl>
        </div>
    </div>

</div>
