
<?php
$this->headTitle('云负载均衡');
$this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>

<div class="productwr">
    <div class="productwr1_5"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>
                    申请流程
                </dt>
                <dd>
                    <a href="/manager">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_13">
                <dt>无缝的业务伸缩</dt>
                <dd>
                    当业务压力增加的时候，可通过向后端服务器池中添加主机来提升性能，当压力降低时，可减少主机，整个伸缩过程对相关调用或访问者不产生影响。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_12">
                <dt>低成本</dt>
                <dd>与传统模式相比省去了添加高昂设备的开支，免运维，大大降低成本。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_14">
                <dt>安全稳定</dt>
                <dd>
                    即使是在负载很重的情况下，服务器也能做出快速响应，专业防Ddos攻击，多用户资源隔离，确保服务安全稳定。


                </dd>
            </dl>
        </div>
    </div>


</div>