<?php
    $this->headTitle('主页');
    $this->headTitle(' - 云上云', 'APPEND');
?>
<div class="main">
    <div class="w1000">
        <h5>混合云管理平台</h5>

        <p>私有云，定制云，腾讯云，阿里云，ucloud统一管理平台<br/>
            统一管理、统一监控、统一调度</p>
        <img src="/towcloud/images/new/main1.png" style="padding-left:150px;">
        <h5 class="h52">云上云联盟</h5>

        <p class="p2">加入云上云联盟、<br/>
            闲置资源(dc,服务器等)<br/>
            一键生成云资源<br/>
            进行统一销售、<br/>
<span>降低企业运营成本<br/>
当企业有突发资源需求时<br/>
可低价采购云上云联盟云资源</span></p>
        <img src="/towcloud/images/new/main2.png" style="margin-top:-280px;">
        <h5>云上云联盟资源</h5>

        <p>云主机、 云cdn、云存储、云数据库</p>
        <img src="/towcloud/images/new/main3.png" style="padding-left:380px;">
    </div>
</div>
<!--<div class="ruzhuanli">
    <h5>入住案例</h5>
    <ul>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli1.png"></a>

            <p>黑猫警长</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli2.png"></a>

            <p>撸塔传奇</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli3.png"></a>

            <p>地下城传说</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli4.png"></a>

            <p>征途口袋版</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli5.png"></a>

            <p>FM一球成名</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli6.png"></a>

            <p>马上三国</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli7.png"></a>

            <p>大骑士传说</p>
        </li>
        <li>
            <a href="javascript:void(0)"><img src="/towcloud/images/new/ruzhuanli8.png"></a>

            <p>江湖HD</p>
        </li>
    </ul>
</div>-->
<div class="chanpingfuwu">
    <h5>产品服务</h5>
    <ul>
        <a href="/yfwq" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu1.png">云主机</h6>

                <P>10年主机产品运营经验，高性能，低成本服务器，大规模分布式计算系统，通过虚拟化技术整合IT资源</P>
            </li>
        </a>
        <a href="/cdn" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu2.png">云分发CDN</h6>

                <P>CDN服务将网站静态内容发布于离用户最近节点，用户可就近获得数据，提高页面访问速度和下载速度；广泛的CDN节点分布，保障用户的极致体验。</P>
            </li>
        </a>
        <a href="/ysjk" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu3.png">云数据库</h6>

                <P>提供各种云端数据库服务，通过简单的网页操作，用户可以方便地对数据库进行创建及设置，操作与扩展变得轻松简单。</P>
            </li>
        </a>
        <a href="/yaq" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu4.png">云安全</h6>

                <P>用户只需开通或简单配置云安全，即可获得全面的云安全服务。云安全系统仅在集群内检测访问URL和访问日志，安全可靠。</P>
            </li>
        </a>
        <a href="/yjk" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu5.png">云监控</h6>

                <P>全面有效的监控方式对CPU、内存、负载、磁盘、网卡流量，以及后续更多高级的监控项，全面呵护你的服务器。</P>
            </li>
        </a>
        <a href="/fzjh" title="点击查看详情" target="_blank">
            <li>
                <h6><img src="/towcloud/images/new/chanpingfuwu6.png">负载均衡</h6>

                <P>当业务压力增加的时候，可通过向后端服务器池中添加主机来提升性能，当压力降低时，整个伸缩过程对相关调用或访问者不产生影响。</P>
            </li>
        </a>
    </ul>
</div>
<div class="hangyexinwen">
    <h5>行业新闻</h5>
    <ul>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-21/2826521">[12-21]专访普元CTO焦烈焱：传统企业在大数据时代的玩法</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-16/2826497">[12-16]谷歌发布更快更灵活的云端SQL数据库服务</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-14/2826463">[12-14]IDC对2016年大数据、云计算等领域的7个预测</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-12/2826458">[12-12]【BDTC
                2015】社会治理大数据分论坛：大数据优势助力社会治理领域创新</a></li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-10/2826448">[12-10]EC2专用主机现在可用</a></li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-10/2826442">[12-10]京东云平台总架构师、系统技术部负责人刘海锋：从2014到2016，大规模内存数据库演进之路</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-10/2826440">[12-10]IBM副总裁、大中华区硬件系统部总经理郭仁声：未来的认知工作负载需要全新的IT基础架构</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-10/2826436">[12-10]阿里巴巴集团CTO王坚：互联网、数据和计算</a>
        </li>
        <li><a target="_blank" href="http://www.csdn.net/article/2015-12-10/2826441">[12-10]中国工程院院士高文：多媒体大数据分析与搜索</a>
        </li>
    </ul>
</div>
<div class="hezuohuoban">
    <h5>合作伙伴</h5>
    <ul>
        <ul>
            <!--<li><a><img src="/towcloud/images/new/hezuohuoban1.png"></a></li>-->
            <li><a><img src="/towcloud/images/new/hezuohuoban2.png"></a></li>
            <li><a><img src="/towcloud/images/new/hezuohuoban3.png"></a></li>
            <li><a><img src="/towcloud/images/new/hezuohuoban4.png"></a></li>
        </ul>
    </ul>
</div>
<div class="footer">
    <h5>联系我们</h5>
    <ul>
        <li><img src="/towcloud/images/new/footer1.png">田林路388号新业大楼1013室</li>
        <li><img src="/towcloud/images/new/footer2.png">+(86)021-64858051</li>
        <li><img src="/towcloud/images/new/footer3.png"><a href="mailto:contact@ztgame.com">kefu@twocloud.cn </a></li>
    </ul>
</div>
