<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册 - 云上云</title>
    <link rel="stylesheet" type="text/css" href="/towcloud/css/new/css.css">
    <link rel="stylesheet" type="text/css" href="/towcloud/css/new/bootstrap.min.css">
    <script src="/towcloud/js/jquery-1.12.1.min.js"></script>
    <style>
        .page {
            width: 450px;
            height: 430px;
            background: rgba(44, 51, 61, 0.6);
            position: absolute;
            left: 50%;
            margin-left: -225px;
            top: 200px;
            overflow: hidden;
            -moz-border-radius: 6px;
            -webkit-border-radius: 6px;
            border-radius: 6px;
            padding: 0 70px;
            padding-top: 39px;
        }

        form label {
            color: #f5f5f5;
        }
    </style>
</head>
<body style="background: #1a0001 url(/towcloud/images/bg.jpg) no-repeat left top">
<div class="top" style="background-color: #000000;">
    <div class="w1000">
        <h1 style="padding-top: 0px;margin-top: 10px;"><a href=""><img style="height:70px;" src="/towcloud/images/new/logo-3.png" alt="云上云"></a>
        </h1>
        <dl>
            <dl>
                <dt>
                    <a href="/">首页</a>
                    <a href="/submit-resource">加入云联盟</a>
                    <a href="/manager">采购云资源</a>
                    <a href="/resource">管理云资源</a>
                    <a href="/about">关于我们</a>
                </dt>

                <dd>
                    <a href="login">登录</a>
                    /
                    <a href="/register">注册</a>
                </dd>
            </dl>
        </dl>
    </div>
</div>
<div class="content" style="display: none;">
    <div class="page page-front">
        <div class="page-content">
            <form class="register">
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" autocomplete="off" id="username" name="username"
                           maxlength="10" placeholder="用户名(6-10位的下划线、数字和字母)">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" autocomplete="off" id="password" name="password"
                           placeholder="密码,8-20位大小写字母、数字和特殊字符(#$%^&*@!)" maxlength="20">
                </div>
                <div class="form-group">
                    <label for="cPassword">确认密码</label>
                    <input type="password" class="form-control" autocomplete="off" id="cPassword" name="cPassword"
                           placeholder="确认密码" maxlength="20">
                </div>
                <div class="form_element form-group">
                    <?php
                    $captcha = $form->get('captcha');
                    $formLabel = $this->plugin('formLabel');
                    echo $formLabel->openTag() . $captcha->getOption('label');
                    echo $formLabel->closeTag();
                    ?>
                    <?php
                    /** @var \Zend\Form\View\Helper\Captcha\Image $helper */
                    $helper = $this->plugin($captcha->getCaptcha()->getHelperName());

                    $helper->setCaptchaPosition(\Zend\Form\View\Helper\Captcha\AbstractWord::CAPTCHA_PREPEND);
                    $helper->setSeparator('<br>');
                    echo $helper($captcha);
                    ?>
                </div>
                <?php echo $this->formElement($form->get('security')) ?>
                <button type="submit" class="btn btn-primary btn-block">注册</button>
            </form>

        </div>
    </div>
</div>
<script>
    $(function () {
        setTimeout(function () {
            $(".content").show("slow");
        }, 200);

        var $loginForm = $(".register");
        $loginForm.submit(function () {
            var username = $loginForm.find('input[name=username]').val();
            var password = $loginForm.find('input[name=password]').val();
            var cPassword = $loginForm.find('input[name=cPassword]').val();
            if (!username) {
                alert('用户名不能为空');
                return false;
            }
            if (!password) {
                alert('密码不能为空');
                return false;
            }
            if (password != cPassword) {
                alert('两次密码不相同');
                return false;
            }
            $.post(
                'register-index',
                $loginForm.serializeArray(),
                function (ret) {
                    if (ret.code == 0) {
                        alert('注册成功,继续登录');
                        location.href = "login";
                    } else {
                        if (ret.error) {
                            alert(ret.error);
                        } else {
                            alert('注册失败');
                        }
                        if(ret.code == 2)
                        {
                            $("#register-captcha-image").click();
                        }
                    }
                },
                'json'
            );
            return false;
        });
        $("#register-captcha-image").click(function(){
            $.get(
                '/refresh-captcha',
                {},
                function(ret){
                    $("#register-captcha-image").attr('src','/images/captcha/' + ret.id + '.png');
                    $('#register-captcha-hidden').val(ret.id);
                },
                'json'
            )
        });
    });
</script>
</body>
</html>