<?php
$this->headTitle('加入云联盟');
?>
<div class="top">
    <div class="w1000">
        <h1><a href=""><img src="/towcloud/images/new/logo.png" alt="云上云"></a></h1>
        <dl>
            <dl>
                <dt>
                    <a href="/">首页</a>
                    <a href="/submit-resource">加入云联盟</a>
                    <a href="/manager">采购云资源</a>
                    <a href="/resource">管理云资源</a>
                    <a href="/about">关于我们</a>
                </dt>
                <dd>
                    <a href="/login"
                       target="_blank">登录</a>
                    /
                    <a href="/register">注册</a>
                </dd>
            </dl>

        </dl>
    </div>
</div>
<div class="banner">
    <img src="/towcloud/images/new/banner2.png">
</div>
<div class="nav">
    <a class="cur">管理首页</a>
    <a>推荐产品</a>
    <a>产品热点</a>
    <a>弹性计算</a>
    <a>云服务器ECS</a>
</div>
<div class="redianziyuan">
    <div class="w1000">
        <h2>热点资源</h2>
        <ul>
            <li>
                <img src="/towcloud/images/new/redianziyuan6.png">
                <h5>云上云主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <li>
                <img src="/towcloud/images/new/redianziyuan1.png">
                <h5>阿里云主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <li>
                <img src="/towcloud/images/new/redianziyuan2.png">
                <h5>腾讯云主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <li class="cur">
                <img src="/towcloud/images/new/redianziyuan3.png">
                <h5>亚马逊主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <li>
                <img src="/towcloud/images/new/redianziyuan4.png">
                <h5>Windows主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <li>
                <img src="/towcloud/images/new/redianziyuan5.png">
                <h5>UCloud主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>
            <!--<li>
                <img src="/towcloud/images/new/redianziyuan6.png">
                <h5>阿里云主机</h5>
                <a>提交闲置云资源</a>
                <span></span>
            </li>-->
        </ul>
    </div>
</div>
<div class="footer">
    <h5>联系我们</h5>
    <ul>
        <li><img src="/towcloud/images/new/footer1.png">上海市松江区中辰路655号</li>
        <li><img src="/towcloud/images/new/footer2.png">+(86)021-33979999</li>
        <li><img src="/towcloud/images/new/footer3.png"><a href="mailto:contact@ztgame.com">lianbo@ztgame.com </a></li>
    </ul>
</div>
