<?php
$this->headTitle('云安全');
$this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>
<div class="productwr">
    <div class="productwr1_3"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>申请流程</dt>
                <dd>
                    <a href="/manager">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_8">
                <dt>免部署免维护</dt>
                <dd>无需为你的云服务器购买昂贵安全设备、配置专业安全团队，拥有星云服务器即可开通云安全服务，获得全系列一站式安全保护。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_7">
                <dt>操作简易安全</dt>
                <dd>用户只需开通或简单配置云安全，即可获得全面的云安全服务。云安全系统仅在集群内检测访问URL和访问日志，安全可靠。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_9">
                <dt>贴心管理服务</dt>
                <dd>
                    通过主动防御和风险提醒方式，对DDoS和密码暴力破解提供实时防护和提醒，同时定期对网站潜在的风险进行检测和提醒，解除您的一切安全顾虑。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_8">
                <dt>多层防御体系</dt>
                <dd>网络层提供流量清洗中心，主机层提供客户端防护功能。应用，数据层提供防火墙功能。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_10">
                <dt>海量数据分析</dt>
                <dd>收集攻击行为数据，深入挖掘海量数据，分析判断安全趋势决定防护决策。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_9">
                <dt>专业团队保障</dt>
                <dd>具有多年运营经验与历练可靠的安全团队倾力打造，共同为云安全的用户提供更多、更好的安全产品。让您放心托付。</dd>
            </dl>
        </div>
    </div>
</div>
