<?php
$this->headTitle('云服务器');
$this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>

<div class="productwr">
    <div class="productwr1"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>
                    申请流程
                </dt>
                <dd>
                    <a href="/manager">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_1">
                <dt>强劲稳定</dt>
                <dd>
                    高性能，高可用，高安全，拥有数千台服务器的资源池，完美支持冷热迁移，系统可靠性达99.95%以上


                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_1">
                <dt>高性价比</dt>
                <dd>灵活方便的付款组合，性价比在同行服务中极具竞争力，缩减您的IT总成本！</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_2">
                <dt>安全可靠</dt>
                <dd>
                    为每个主机组提供防火墙功能，通过网络层安全控制，全面防护，保护云主机安全。多重实时副本保障您的数据安全，外加异机备份，彻底避免单点故障，让您的数据安全高枕无忧！
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_2">
                <dt>高性价比</dt>
                <dd>10年专业主机运营经验，机房实地应急响应。完善的平台，让您不懂技术也能使用</dd>
            </dl>
        </div>
    </div>
</div>