
<?php
$this->headTitle('云监控');
$this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>

<div class="productwr">
    <div class="productwr1_2"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>
                    申请流程
                </dt>
                <dd>
                    <a href="/manager">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_3">
                <dt>服务器性能</dt>
                <dd>
                    全面有效的监控方式对CPU、内存、负载、磁盘、网卡流量，以及后续更多高级的监控项，全面呵护你的服务器。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_3">
                <dt>网站性能</dt>
                <dd>提供网站访问全景数据，精准分析网站请求。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_4">
                <dt>实时故障告警</dt>
                <dd>
                    我们支持多种报警方式（云监测网页控制台，短信，邮件），一旦出现运行故障或性能指标达到告警阀值，告警信息就会自动发送，让您第一时间得到异常反馈。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_4">
                <dt>降低运维成本</dt>
                <dd>全面监控服务器、应用和网络设备，简化运维工作。</dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_5">
                <dt>多种视图，报表丰富</dt>
                <dd>
                    帮助用户从不同角度监视IT业务。
                </dd>
            </dl>
        </div>
    </div>
</div>
