
<?php
$this->headTitle('云数据库');
$this->layout()->cssStyles = ['/towcloud/css/yfwq.css'];
?>

<div class="productwr">
    <div class="productwr1_4"></div>
    <div class="productwr2">
        <div class="w1000">
            <dl class="productwr2_1">
                <dt>
                    申请流程
                </dt>
                <dd>
                    <a href="/manager">立即申请</a>
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_11">
                <dt>性能出色</dt>
                <dd>
                    针对数据库高性能需求，采用高端高性能硬件配置,同时对数据库性能参数做了特定的优化。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_10">
                <dt>管理便捷</dt>
                <dd>提供各种云端数据库服务，通过简单的网页操作，用户可以方便地对数据库进行创建及设置，操作与扩展变得轻松简单。
                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr3">
        <div class="w1000">
            <dl class="productwr3_12">
                <dt>自动备份</dt>
                <dd>
                    自动备份您的数据库, 防止数据丢失和误删除，保障您的数据安全可靠。


                </dd>
            </dl>
        </div>
    </div>
    <div class="productwr4">
        <div class="w1000">
            <dl class="productwr4_11">
                <dt>兼容易扩展</dt>
                <dd>  兼容的所有应用，不需要做任何改动，就可将应用程序迁移至云数据库上。可以非常方便地根据数据库的实际负载情况而进行实例的升级，从而获取更高数据库空间与性能。</dd>
            </dl>
        </div>
    </div>

</div>
